title: Musings and digressions
author: Sreekar Chigurupati
email: chigurupatisreekar@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Jotting down random thoughts on life and work

show_excerpts: false # set to true to show excerpts on the homepage
google_analytics: UA-140873056-1

google:
  search_engine_id: 010168232464612929882:zfcxabb2jei
# Pagination Settings
paginate: 3
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title.html
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sreekarchiguru
    github:  EarthBug
    rss: rss
    # dribbble: jekyll
    facebook: chigurupatisreekar
    # flickr:   jekyll
    instagram: sreekarchigurupati
    linkedin: sreekar-chigurupati
    # pinterest: jekyll
    # youtube: jekyll
    #youtube_channel: UC_noQJHR9gP5NxoVrS5eikg
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-archives

 sass:
   style: compressed
